USE [master]
GO
CREATE DATABASE [dbStudentExamSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbStudentExamSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbStudentExamSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbStudentExamSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbStudentExamSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbStudentExamSystem] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbStudentExamSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbStudentExamSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbStudentExamSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbStudentExamSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dbStudentExamSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbStudentExamSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [dbStudentExamSystem] SET  MULTI_USER 
GO
ALTER DATABASE [dbStudentExamSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbStudentExamSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dbStudentExamSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dbStudentExamSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dbStudentExamSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dbStudentExamSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbStudentExamSystem', N'ON'
GO
ALTER DATABASE [dbStudentExamSystem] SET QUERY_STORE = OFF
GO
USE [dbStudentExamSystem]

GO
CREATE TABLE "UserTypes" (
	"UserTypeID" "int" IDENTITY (1, 1) NOT NULL ,
	"UserTypeName" nvarchar (50) NOT NULL ,
	CONSTRAINT "PK_UserTypes" PRIMARY KEY  CLUSTERED 
	(
		"UserTypeID"
	)
)

GO
CREATE TABLE "Users" (
	"UserID" "int" IDENTITY (1, 1) NOT NULL ,
	"UserName" nvarchar (50) NOT NULL ,
	"Name" nvarchar (50) NULL ,
	"Surname" nvarchar (50) NULL ,
	"Mail" nvarchar (50) NULL ,
	"Password" nvarchar (50) NOT NULL ,
	"UserTypeID" "int" NOT NULL ,
	CONSTRAINT "PK_Users" PRIMARY KEY  CLUSTERED 
	(
		"UserID"
	),
	CONSTRAINT "FK_Users_UserTypes" FOREIGN KEY 
	(
		"UserTypeID"
	) REFERENCES "dbo"."UserTypes" (
		"UserTypeID"
	)
)

INSERT "UserTypes"("UserTypeName") VALUES('Admin')
INSERT "UserTypes"("UserTypeName") VALUES('Sýnav Sorumlusu')
INSERT "UserTypes"("UserTypeName") VALUES('Öðrenci')

INSERT "Users"("UserName","Name","Surname","Mail","Password","UserTypeID") VALUES('Admin','Yusuf','Ekin','yusuf3456@gmail.com','abc123',1)